#!/bin/bash

function filter {
  aws emr list-clusters \
  | jq ".Clusters[] | select(.Name | contains(\"$1\")) | {Name:.Name, Id:.Id}"
}

function list {
  aws emr list-clusters \
  | jq ".Clusters[] | {
                Name:.Name,
                Id:.Id,
                Status:.Status.State,
                Created:.Status.Timeline.CreationDateTime | todate
              }"
}

function info {
  aws emr describe-cluster --cluster-id "$(get-id $1)"
}

function terminate {
  aws emr terminate-clusters --cluster-ids "$(get-id $1)"
}

function get-id {
  echo "$(filter $1 | jq -r '.Id')"
}

# some common jq filter
function list-recent { list | jq -s "sort_by(.Created) | reverse | .[0:${1:-5}] | .[]"; }
function list-active { list-waiting; } # common typo for me
function list-waiting { list | jq 'select(.Status=="WAITING")'; }
function list-terminating { list | jq 'select(.Status=="TERMINATING")'; }
function list-bootstrapping { list | jq 'select(.Status=="BOOTSTRAPPING")'; }
function list-starting { list | jq 'select(.Status=="STARTING")'; }


echo "$($@)"

